version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend_api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://database:27017/tasks_db
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
